sudo: required
services:
  - docker

before_install:
  - docker build -t dcampost89/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dcampost89/react-test npm test -- --coverage

after_success:
  - docker build -t dcampost89/multi-client ./client
  - docker build -t dcampost89/multi-nginx ./nginx
  - docker build -t dcampost89/multi-server ./server
  - docker build -t dcampost89/multi-worker ./worker
  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push dcampost89/multi-client
  - docker push dcampost89/multi-nginx
  - docker push dcampost89/multi-server